### PR TITLE
Move initialization properly into GameScene.sks

### PR DESCRIPTION
**Pull request by EtherTyper**

### CODE REVIEW

**Comment by EtherTyper** [comment]
@WestlakeAPC/flappy-smasher Please clone and review.

**Comment by AnimatorJoe** [comment]
Great job! The character moves and functions the way it should! :) Just try to resize and place everything correctly. I would recommend using code from the older version of game scene.swift (59 - 96), at least for when the sprite placement and properties are specified. I know you want to do that in the sks, but for the placement, size and various other properties of the sprites, I would say the code is more reliable. Overall, good job! :)

**Review by AnimatorJoe — CHANGES_REQUESTED** [review]
The Tim chart seems to be a little stretched, and the sword is firing out a bit lower than they should. The graphics property assignments (aSpriteName.something = something) shouldn't slow things down too much, so maybe add that back, but keep the character initialization on the sks.

**Comment by EtherTyper** [comment]
@AnimatorJoe Graphics property assignments will be fixed in GameScene.sks. Thanks for the suggestions.

**Comment by EtherTyper** [comment]
@AnimatorJoe I tested it, and it works now. 😆

**Comment by EtherTyper** [comment]
@AnimatorJoe Please re-review.

**Review by AnimatorJoe — COMMENTED** [review]
I am glad you have made so much progress as well as keeping up with my changes lately! :) The score board is not centered on the screen for me for some reason, if it is for you, then maybe it's because we are using different Xcode versions, or else IDK. I would suggest setting the displayScore.position in code to CGPoint(x: self.size.width/2, y: /_Something_/) since that would guaranteed correct placement. The sword is firing out from the right place this time, which is good :D! For some reason, the birds aren't just generating on the screen, but also slightly and many probably off the screen. If you run my code, there would be around 240 nodes at max, but your code seems to reach around 330 because of this problem. I don't know why this is happening, but I think it's something in the randomBirdPosY calculation that is going wrong. What you are trying to do is very difficult and I appreciate your hard work! Overall the code has improved greatly. :D

**Comment by EtherTyper** [comment]
@AnimatorJoe More birds spawn most likely due to the change of bird scope. They now spawn in `backgroundImage` instead of `self`, which isn't a problem, I believe.

**Comment by EtherTyper** [comment]
@AnimatorJoe The avg. bird count is now ~143, with my latest commit, which sets the `backgroundImage` y-values on screen. As for the score board, it's centered on the `backgroundImage`, like it's supposed to be. It will show up reliably on other devices this way, though maybe not in the same place on all of them. (Remember how our Death Dodger scoreboard failed to show on tvOS or iPads?)

**Review by AnimatorJoe — APPROVED** [review]

**Pull request merged**
